<a href="https://colab.research.google.com/github/DommiiUdomp/-/blob/main/MetricsKeras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Metrics in Keras**

In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
import tensorflow.keras.backend as K

In [12]:
model = Sequential ( [
                      Flatten (input_shape = (28,28)) , 
                      Dense (32 , activation = 'relu') ,
                      Dense (32, activation = 'tanh') ,
                      Dense (10, activation = 'softmax')
])

model.compile ( optimizer = 'adam' ,
               loss = 'sparse_categorical_crossentropy' ,
               metrics = ['accuracy' , 'mae'] )

print (model.optimizer)
print (model.loss)
print (model.metrics)

sparse_categorical_crossentropy
[]


In [23]:
## Specify k instead with the sparse top-k categorical accuracy

model2 = Sequential ( [ 
                       Flatten (input_shape = (28,28)) ,
                       Dense (64, activation = 'relu') ,
                       Dense (64, activation = 'tanh') ,
                       Dense (10, activation = 'softmax')
])

model2.compile ( optimizer = tf.keras.optimizers.Adam(learning_rate=0.001 , beta_1 = 0.9) ,
                loss = tf.keras.losses.sparse_categorical_crossentropy ,
                metrics = [tf.keras.metrics.SparseTopKCategoricalAccuracy(k=3) ] )

In [24]:
print (model2.optimizer)
print (model2.loss)
print (model2.metrics)

<function sparse_categorical_crossentropy at 0x7f681e725b90>
[]


# **Case 1 - Binary Classification with sigmoid activation function**

In [19]:
# Sigmoid activation function

y_true = tf.constant([0.0,1.0,1.0])
y_pred = tf.constant([0.4,0.8, 0.3])
accuracy = K.mean(K.equal(y_true, K.round(y_pred)))
accuracy

<tf.Tensor: shape=(), dtype=float32, numpy=0.6666667>

# **Case 2 - Categorical Classification**

In the backend of Keras, the accuracy metric is implemented slightly differently depending on whether we have a binary classification problem ( 𝑚=2 ) or a categorical classifcation problem. Note that the accuracy for binary classification problems is the same, no matter if we use a sigmoid or softmax activation function to obtain the output.

In [20]:
# Binary classification with softmax

y_true = tf.constant([[0.0,1.0], [1.0,0.0], [1.0,0.0], [0.0,1.0]])
y_pred = tf.constant([[0.4,0.6], [0.3,0.7], [0.05,0.95],[0.33,0.67]])
accuracy =K.mean(K.equal(y_true, K.round(y_pred)))
accuracy

<tf.Tensor: shape=(), dtype=float32, numpy=0.5>

In [21]:
# Categorical classification with m>2

y_true = tf.constant([[0.0,1.0,0.0,0.0],[1.0,0.0,0.0,0.0],[0.0,0.0,1.0,0.0]])
y_pred = tf.constant([[0.4,0.6,0.0,0.0], [0.3,0.2,0.1,0.4], [0.05,0.35,0.5,0.1]])
accuracy = K.mean(K.equal(K.argmax(y_true, axis=-1), K.argmax(y_pred, axis=-1)))
accuracy

<tf.Tensor: shape=(), dtype=float32, numpy=0.6666667>

# **Other examples of metrics**

**Custom metrics**

In [25]:
# Define a custom metric

def mean_pred(y_true, y_pred):
    return K.mean(y_pred)

In [26]:
# Specify k instead with the sparse top-k categorical accuracy

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=[mean_pred])

**Multiple metrics**

In [27]:
# Compile the model with multiple metrics

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=[mean_pred, "accuracy",tf.keras.metrics.SparseTopKCategoricalAccuracy(k=3)])